#!/usr/bin/python3
from hackeriet import vending

while True:
    input("Dra kort: ")
    print("Velg produkt")
    s = vending.select_product()
    print("%d valgt" % s)
    vending.vend_product(s)


