#!/usr/bin/env python

import config
import mifare
from users.users import Users
import uuid
import sys

users = Users()

if hasattr(config, "keyA"): mifare.keyA = config.keyA
if hasattr(config, "keyB"): mifare.keyB = config.keyB

d = users.get_card_data(sys.argv[0])
print(d)

mifare.wait_card()
mifare.write_sector(d, 7)

print(users.get_card_user(mifare.read_sector(7)[0:16]))



